ping affiliate.colmexpro.com -n 1 > c:\www_statistics.txt
ping www.tradenet.de -n 1 >> c:\www_statistics.txt
ping tradenet.de -n 1 >> c:\www_statistics.txt
ping tradenet.com -n 1 >> c:\www_statistics.txt
ping www.tradenet.com -n 1 >> c:\www_statistics.txt
ping fstradenet.com -n 1 >> c:\www_statistics.txt
ping www.fstradenet.com -n 1 >> c:\www_statistics.txt
ping tradenetcapitalmarkets.com -n 1 >> c:\www_statistics.txt
ping www.tradenetcapitalmarkets.com -n 1 >> c:\www_statistics.txt
ping interactivet.com	 -n 1 >> c:\www_statistics.txt
ping www.interactivet.com	 -n 1 >> c:\www_statistics.txt
ping tefsec.com -n 1 >> c:\www_statistics.txt
ping www.tefsec.com -n 1 >> c:\www_statistics.txt
ping realinvest.today -n 1 >> c:\www_statistics.txt
ping www.realinvest.today -n 1 >> c:\www_statistics.txt
ping tradenetcapitalmarkets.de -n 1 >> c:\www_statistics.txt
ping www.tradenet.jp -n 1 >> c:\www_statistics.txt
ping tradenet.jp -n 1 >> c:\www_statistics.txt
ping tradenet.in -n 1 >> c:\www_statistics.txt
ping www.tradenet.in -n 1 >> c:\www_statistics.txt
ping tradenetacademy.ru -n 1 >> c:\www_statistics.txt
ping www.tradenetacademy.ru -n 1 >> c:\www_statistics.txt
ping tradenetacademy.co -n 1 >> c:\www_statistics.txt
ping services.colmexpro.com -n 1 >> c:\www_statistics.txt
ping services.cglms.com -n 1 >> c:\www_statistics.txt
ping services.cglms.com -n 1 >> c:\www_statistics.txt
ping cmp.colmexpro.com -n 1 >> c:\www_statistics.txt
ping cmp.colmexpro.com -n 1 >> c:\www_statistics.txt
ping http:/affiliate.colmexpro.com -n 1 >> c:\www_statistics.txt
ping affiliate.colmexpro.com -n 1 >> c:\www_statistics.txt
ping payment.fstradenet.com -n 1 >> c:\www_statistics.txt
ping payment.tradenetcapitalmarkets.com -n 1 >> c:\www_statistics.txt
ping payment.fstradenet.com -n 1 >> c:\www_statistics.txt
ping payment.tradenetcapitalmarkets.com -n 1 >> c:\www_statistics.txt
ping affiliatesbackoffice.cglms.com -n 1 >> c:\www_statistics.txt
ping moodle.cglms.com -n 1 >> c:\www_statistics.txt
ping moodle.cglms.com -n 1 >> c:\www_statistics.txt
ping kpi.tradenet.local -n 1 >> c:\www_statistics.txt
ping CglOfferGenerator.cglms.com -n 1 >> c:\www_statistics.txt
ping services.colmex.co.il -n 1 >> c:\www_statistics.txt
ping services.colmex.co.il -n 1 >> c:\www_statistics.txt
ping public.cglms.com -n 1 >> c:\www_statistics.txt
ping public.cglms.com -n 1 >> c:\www_statistics.txt
ping local.cglms.com -n 1 >> c:\www_statistics.txt
ping local.cglms.com -n 1 >> c:\www_statistics.txt
ping services.tradenet.com -n 1 >> c:\www_statistics.txt
ping services.tradenet.com -n 1 >> c:\www_statistics.txt
ping wp.mytradingstyle.com -n 1 >> c:\www_statistics.txt
ping www.mytradingstyle.com -n 1 >> c:\www_statistics.txt
ping www.cglms.com -n 1 >> c:\www_statistics.txt
ping www.colmexpm.co.il -n 1 >> c:\www_statistics.txt
ping colmexpm.co.il -n 1 >> c:\www_statistics.txt
ping www.colmexinforum.com -n 1 >> c:\www_statistics.txt
ping colmexinforum.com -n 1 >> c:\www_statistics.txt
ping colmex.co -n 1 >> c:\www_statistics.txt
ping www.colmex.co -n 1 >> c:\www_statistics.txt
ping tradenet.academy -n 1 >> c:\www_statistics.txt
ping www.tradenet.academy -n 1 >> c:\www_statistics.txt
ping colmex.biz -n 1 >> c:\www_statistics.txt
ping www.colmex.biz -n 1 >> c:\www_statistics.txt
ping r.colmex.co.il -n 1 >> c:\www_statistics.txt
ping r.colmex.co.il -n 1 >> c:\www_statistics.txt
ping tradenet.reviews -n 1 >> c:\www_statistics.txt
ping www.tradenet.reviews -n 1 >> c:\www_statistics.txt
ping www.colmex.trade -n 1 >> c:\www_statistics.txt
ping colmex.trade -n 1 >> c:\www_statistics.txt
ping mtstest.colmex.co.il -n 1 >> c:\www_statistics.txt
ping mtstest.colmex.co.il -n 1 >> c:\www_statistics.txt
ping r.tradenet.com -n 1 >> c:\www_statistics.txt
ping lp.tradenet.com -n 1 >> c:\www_statistics.txt
ping https/lp.tradenet.com -n 1 >> c:\www_statistics.txt
ping lp.colmexpro.com -n 1 >> c:\www_statistics.txt
ping lp.colmexpro.com -n 1 >> c:\www_statistics.txt
ping 1000affiliatesclub.com -n 1 >> c:\www_statistics.txt
ping 1000affiliatesclub.com -n 1 >> c:\www_statistics.txt
ping downloads.tefsec.com -n 1 >> c:\www_statistics.txt
ping https/downloads.tefsec.com -n 1 >> c:\www_statistics.txt
ping lp.tradenet.de -n 1 >> c:\www_statistics.txt
ping promo.tradenet.de-n 1 >> c:\www_statistics.txt
ping wlp.tradenet.de -n 1 >> c:\www_statistics.txt
ping promo.tradenet.de -n 1 >> c:\www_statistics.txt
ping lp.colmex.co.il -n 1 >> c:\www_statistics.txt
ping lp.colmex.co.il -n 1 >> c:\www_statistics.txt
ping sign.fstradenet.com -n 1 >> c:\www_statistics.txt
ping sign.fstradenet.com -n 1 >> c:\www_statistics.txt
ping sign.tradenetcapitalmarkets.com -n 1 >> c:\www_statistics.txt
ping sign.tradenetcapitalmarkets.com -n 1 >> c:\www_statistics.txt
ping lp.finanzenjournal.com -n 1 >> c:\www_statistics.txt
ping finanzenjournal.com -n 1 >> c:\www_statistics.txt
ping lp.finanzenjournal.com -n 1 >> c:\www_statistics.txt
ping finanzenjournal.com -n 1 >> c:\www_statistics.txt
ping qaz.tradenetlondon.com -n 1 >> c:\www_statistics.txt
ping www.tradenetlondon.com -n 1 >> c:\www_statistics.txt
ping tradenetlondon.com -n 1 >> c:\www_statistics.txt
ping tradenetlondon.co.uk -n 1 >> c:\www_statistics.txt
ping www.tradenetlondon.co.uk -n 1 >> c:\www_statistics.txt
ping tefsec.com -n 1 >> c:\www_statistics.txt
ping www.tefsec.com -n 1 >> c:\www_statistics.txt
ping www.colmexpro.com -n 1 >> c:\www_statistics.txt
ping colmexpro.com -n 1 >> c:\www_statistics.txt
ping colmexpro.com -n 1 >> c:\www_statistics.txt
ping www.colmexpro.com -n 1 >> c:\www_statistics.txt
ping books.tradenet.com -n 1 >> c:\www_statistics.txt
ping books.tradenet.com -n 1 >> c:\www_statistics.txt
ping www.colmexinforum.com -n 1 >> c:\www_statistics.txt
ping colmexinforum.com -n 1 >> c:\www_statistics.txt
ping colmex.co.il -n 1 >> c:\www_statistics.txt
ping www.colmex.co.il -n 1 >> c:\www_statistics.txt
ping www.colmex.co.il -n 1 >> c:\www_statistics.txt
ping colmex.co.il -n 1 >> c:\www_statistics.txt
ping colmexil.valhalla.local -n 1 >> c:\www_statistics.txt
ping crpbycolmex.co.il -n 1 >> c:\www_statistics.txt
ping www.crpbycolmex.co.il -n 1 >> c:\www_statistics.txt
ping www.crpbycolmex.com -n 1 >> c:\www_statistics.txt
ping crpbycolmex.com -n 1 >> c:\www_statistics.txt
ping crpcoil.valhalla.local -n 1 >> c:\www_statistics.txt
ping www.tradenetaffiliates.com -n 1 >> c:\www_statistics.txt
ping aff.tradenet.com -n 1 >> c:\www_statistics.txt
ping wtradenetaffiliates.com -n 1 >> c:\www_statistics.txt
ping go.tradenetaffiliates.com -n 1 >> c:\www_statistics.txt
ping go.colmexaffiliates.com -n 1 >> c:\www_statistics.txt
ping www.colmexaffiliates.com -n 1 >> c:\www_statistics.txt
ping colmexaffiliates.co -n 1 >> c:\www_statistics.txt
ping go.colmexaffiliates.com -n 1 >> c:\www_statistics.txt
ping www.colmexpro.de -n 1 >> c:\www_statistics.txt
ping colmexpro.de -n 1 >> c:\www_statistics.txt
ping colmexpro.de -n 1 >> c:\www_statistics.txt
ping www.colmexpro.de -n 1 >> c:\www_statistics.txt
